# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDay16Q1Dailywise():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_day16Q1Dailywise(self):
    self.driver.get("https://www.selenium.dev/selenium/web/web-form.html")
    self.driver.set_window_size(1280, 720)
    self.driver.find_element(By.ID, "my-text-id").send_keys("Anunay kumar")
    self.driver.find_element(By.NAME, "my-text").send_keys("Selenium IDE Test")
    self.driver.find_element(By.CSS_SELECTOR, "input.form-control").send_keys("Testing Locators")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    time.sleep(1)
    assert self.driver.find_element(By.XPATH, "//h1").text == "Form submitted"
    self.driver.close()
  
